language: ruby
sudo: false
cache: bundler
install: true
script:
  - './script/ci'
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fde2367248d53de4fe70
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start:   never   # options: [always|never|change] default: always
